// All unique contacts from Google Sheets
export const allContacts = [
  {
    firstName: "Nadine",
    middleName: "Jumpdan Epse Mark Phillip",
    lastName: "",
    dob: "7/1/1983",
    gender: "F",
    phone: "(347) 207-4064",
    email: "naddan274@gmail.com",
    address: "2300 Grand Concourse, Apt 4D",
    city: "Bronx",
    state: "NY",
    zip: "10458-6924",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Rubi",
    middleName: "Chamorro Moroch",
    lastName: "",
    dob: "4/20/2023",
    gender: "F",
    phone: "(347) 261-9800",
    email: "",
    address: "43 Duryea Ave Apt #2",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Virginia",
    middleName: "JimenezDeBautista",
    lastName: "",
    dob: "6/26/1957",
    gender: "F",
    phone: "(914) 800-5453",
    email: "",
    address: "18 S Bleeker St, Apt 4",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550-2471",
    language: "Spanish",
    status: "Active"
  },
  {
    firstName: "Taneshia",
    middleName: "Chambers",
    lastName: "",
    dob: "5/28/2000",
    gender: "F",
    phone: "(914) 530-5601",
    email: "",
    address: "150 S 2nd Ave # 1A",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Jared",
    middleName: "Smith",
    lastName: "",
    dob: "9/13/2002",
    gender: "M",
    phone: "(914) 363-9082",
    email: "",
    address: "123 S 12th Ave, Apt 2",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550-2914",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Van",
    middleName: "Kelley",
    lastName: "",
    dob: "7/26/1969",
    gender: "M",
    phone: "(914) 497-3124",
    email: "",
    address: "4111 Baychester Ave",
    city: "Bronx",
    state: "NY",
    zip: "10466-2121",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Christopher",
    middleName: "Doyle",
    lastName: "",
    dob: "12/30/1993",
    gender: "M",
    phone: "(914) 349-3658",
    email: "",
    address: "16 Glover Ave",
    city: "Yonkers",
    state: "NY",
    zip: "10704-4204",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Hubert",
    middleName: "G",
    lastName: "Harris",
    dob: "9/28/1972",
    gender: "M",
    phone: "(347) 241-9256",
    email: "",
    address: "1319 E 224th St, Apt 3",
    city: "Bronx",
    state: "NY",
    zip: "10466-6091",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Deborah",
    middleName: "J",
    lastName: "Dickerson",
    dob: "1/13/1979",
    gender: "F",
    phone: "(914) 815-8884",
    email: "debdickerson@yahoo.com",
    address: "353 S 5th Ave, Fl 1",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550-4111",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Andres",
    middleName: "Delgado",
    lastName: "",
    dob: "12/19/1968",
    gender: "M",
    phone: "(631) 889-9273",
    email: "",
    address: "1591 E 233rd St, Apt 7",
    city: "Bronx",
    state: "NY",
    zip: "10466-3336",
    language: "English",
    status: "Active"
  },
  {
    firstName: "Jacqueline",
    middleName: "M",
    lastName: "Harris",
    dob: "8/5/1974",
    gender: "F",
    phone: "(914) 800-5453",
    email: "",
    address: "18 S Bleeker St, Apt 4",
    city: "Mount Vernon",
    state: "NY",
    zip: "10550-2471",
    language: "English",
    status: "Active"
  }
  // Add more contacts here as needed...
]; 