// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfhslrzkjgyrxwxlyjyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaHNscnpramd5cnh3eGx5anl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODMwNzUsImV4cCI6MjA2Mzk1OTA3NX0.Z_WdGbmE_K7hmiokgiMq9wbFbT3TA8rSYBaAdShbmBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});